name: Python CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        python-version: [2.7, '3.8', '3.12']
    steps:
    - uses: actions/checkout@v1
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Pull the docker image
      run: make docker-pull

    - name: Create Coverage dest
      run: mkdir -p coverage

    - name: Run Elastic Search
      run: make test.start_elasticsearch

    - name: Run Docker test
      shell: 'script -q -e -c "bash {0}"'
      run: make test-docker

    - name: Run Quality Check
      shell: 'script -q -e -c "bash {0}"'
      run: make quality-docker

    - name: Create Coverage Report
      shell: 'script -q -e -c "bash {0}"'
      run: make coverage-docker

    - name: Run Docs Check
      run: sudo make docs

    - name: Stop elastic search Check
      run: make test.stop_elasticsearch

    - name: Install Codecov
      run: pip install --upgrade codecov

    - name: Run Coverage
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
